[package]
name = "shuttle-map"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
image = "0.24"
noise = "0.7"
rand = "0.8"
rocket = "0.5.0-rc.2"
shuttle-service = { version = "0.5.2", features = ["web-rocket"] }